### PR TITLE
Resume CI with GitHub Actions

### PR DESCRIPTION
**Pull request by jginsburgn**
Fixes https://github.com/karma-runner/integration-tests/issues/17

### CODE REVIEW

**Review by mtrea — CHANGES_REQUESTED** [review]
Please confirm whether we can replace "uses: actions/checkout@v3" with an unversioned entry that's always the latest. Same with "setup-node".

**Comment by jginsburgn** [comment]
> Please confirm whether we can replace "uses: actions/checkout@v3" with an unversioned entry that's always the latest. Same with "setup-node".

@mtrea 

The docs [strongly recommend pinning an action to a version][recommendation]. The reason is related to unexpected behavior changes, but I assume that official (i.e. published by GitHub) actions are stable enough. I am happy using either of `main` (latest) or `v3` latest major. WDYT?

[recommendation]: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#:~:text=We%20strongly%20recommend%20that%20you%20include%20the%20version%20of%20the%20action%20you%20are%20using%20by%20specifying%20a%20Git%20ref%2C%20SHA%2C%20or%20Docker%20tag%20number.

**Review by mtrea — CHANGES_REQUESTED** [review]
I didn't realize they strongly recommend using versions. In that case, I don't have a good reason to go against that. Let's follow their recommendation. That just reminded me of another high-profile case that reinforces this decision: https://www.bleepingcomputer.com/news/security/big-sabotage-famous-npm-package-deletes-files-to-protest-ukraine-war/

**Comment by jginsburgn** [comment]
> I didn't realize they strongly recommend using versions. In that case, I don't have a good reason to go against that. Let's follow their recommendation. That just reminded me of another high-profile case that reinforces this decision: https://www.bleepingcomputer.com/news/security/big-sabotage-famous-npm-package-deletes-files-to-protest-ukraine-war/

@mtrea 

Done.

**Review by mtrea — APPROVED** [review]

**Pull request merged**
